# Maintain code in Azure Repos and automate deployment using Azure CI/CD pipelines.

# azure-pipelines.yml
trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  AZURE_SUBSCRIPTION: 'Your Azure Subscription'
  RESOURCE_GROUP: 'your-resource-group'
  APP_NAME: 'your-app-name'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.8'
    addToPath: true

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: |
    python -m unittest discover tests
  displayName: 'Run tests'

- task: AzureWebApp@1
  inputs:
    azureSubscription: '$(AZURE_SUBSCRIPTION)'
    appName: '$(APP_NAME)'
    package: '$(System.DefaultWorkingDirectory)/**.zip'
  displayName: 'Deploy to Azure Web App'